<ShowWidget>:
    #:set imgdata './Source/image/lefton.png'
    canvas.before:
        Color:
            rgba: 0.95, 0.95, 0.95, 1
        Rectangle:
            pos: self.pos
            size: self.size

    BoxLayout:
        orientation: 'horizontal'
        size: root.size

        BoxLayout:
            orientation: 'vertical'
            #orientation: 'horizontal'
            #size: root.size
            size_hint_x: 425 / root.width

            BoxLayout:
                orientation: 'vertical'
                canvas.before:
                    Color:
                        rgba: 1, 1, 1, 1
                    Rectangle:
                        pos: self.pos
                        size: self.size
                Image:
                    size_hint_y: 725 / 4
                    keep_ratio: True
                    source: './Source/image/commentmierukun.jpg'

                TabbedPanel:
                    do_default_tab: False
                    size_hint_y: 725 * 3 / 4
                    background_color: [0,0,0,0]
                    canvas.before: 
                        Rectangle: 
                            pos: self.pos 
                            size: self.size 
                            #keep_ratio: True
                            source: root.source
                    TabbedPanelItem:
                        text:'ルーム名で\n実行'
                        #size_hint: (None, None) 
                        tab_pos: 'top_mid'
                        color: [0.23,0.23,0.23,1]
                        background_color: [1,1,1,0]
                        font_size: 24
                        #halign: 'center'
                        on_release: root.buttonClickedroom()
                        #:set imgdata './Source/image/lefton.png'
                        BoxLayout:
                            orientation: 'vertical'
                            size_hint_y: 1
                            padding: [50,20, 50, 20]
                            spacing: 25

                            Label:
                                text: "ルーム名"
                                color: [0.23,0.23,0.23,1]
                                size_hint_x: 0
                                size_hint_y: 0.05
                                font_size: 24

                            BoxLayout:
                                orientation: 'horizontal'
                                size_hint_y: 0.2
                                Label:
                                    text: "#"
                                    size_hint_y: 0.7
                                    color: [0.23,0.23,0.23,1]
                                    size_hint_x: 0.1
                                    font_size: 24
                                TextInput:
                                    multiline: True
                                    size_hint_x: 0.9
                                    size_hint_y: 0.7
                                    height: self.line_height + self.padding[1] + self.padding[3] + 10
                                    font_size: 24

                            Label:
                                text: "Error:\nああああああ\nあああ"
                                color: [1,0,0,0]
                                font_size: 24
                                text_size: self.size
                                size_hint_y: 0.5
                                halign: 'left'
                                valign: 'top'
                            BoxLayout:
                                size_hint_y: 0.25
                                orientation: 'vertical'
                                padding: [60,0, 60, 0]
                                Button:
                                    id: button1
                                    background_normal: './Source/image/buttonimg.png'
                                    background_down: './Source/image/downbuttonimg.png'
                                    on_press: root.ids.graph_view.load_scrapingdata()  # ボタンをクリックした時にpython側の関数を呼ぶ
                    TabbedPanelItem:
                        tab_pos: 'top_mid'
                        text: 'ファイルで\n実行'
                        color: [0.23,0.23,0.23,1]
                        #size_hint: (None, None) 
                        background_color: [1,1,1,0]
                        font_size: 24
                        #halign: 'center'
                        on_release: root.buttonClickedfile()
                        #:set imgdata './Source/image/righton.png'
                        BoxLayout:
                            orientation: 'vertical'
                            size_hint_y: 1
                            padding: [50,20, 50, 20]
                            spacing: 25

                            Label:
                                text: "ファイルをドロップ"
                                color: [0.23,0.23,0.23,1]
                                size_hint_y: 0.07
                                size_hint_x: 0.6
                                font_size: 24
                                
                            TextInput:
                                size_hint_x: 1
                                size_hint_y: 0.33
                                text: root.filepath
                                color: [0.23,0.23,0.23,1]
                                font_size: 21
                                text_size: self.size
                                background_normal: './Source/image/nomalimage.png'
                                background_active: './Source/image/nomalimage.png'
                                background_disabled_normal: './Source/image/nomalimage.png'
                                #halign: 'right'
                                #valign: 'middle'

                            Label:
                                text: "Error:\nああああああ\nあああ"
                                color: [1,0,0,0]
                                font_size: 24
                                text_size: self.size
                                size_hint_y: 0.35
                                halign: 'left'
                                valign: 'top'

                            BoxLayout:
                                size_hint_y: 0.25
                                orientation: 'vertical'
                                padding: [60,0, 60, 0]
                                Button:
                                    id: button1
                                    background_normal: './Source/image/buttonimg.png'
                                    background_down: './Source/image/downbuttonimg.png'
                                    #on_press: root.buttonClicked1()  # ボタンをクリックした時にpython側の関数を呼ぶ
                                    #on_press: root.ids.graph_view.init_graph()
                                    #on_press: root.ids.graph_view.load_data()
                                    on_press: root.conpanel()

                BoxLayout:
                    size_hint_y: root.height - 725
                    canvas.before:
                        Color:
                            rgba: 1, 1, 1, 1
                        Rectangle:
                            pos: self.pos
                            size: self.size

        BoxLayout:
            orientation: 'vertical'
            #orientation: 'horizontal'
            #size: root.size
            #size_hint_x: 0.675
            #Image:
            #    source: 'sakotomo.png'
            #    size_hint_y: 0.5
            size_hint_x: 1 - (425 / root.width)
            GraphView:
                id: graph_view
                #size_hint_y: root.height - 300
                size_hint_y: 0.6
            ScrollView:
                size_hint_y: 0.4
                #GridLayout:
                #    cols:1
                #    size_hint_y: None
                #    row_default_height: 200
                #    height: self.minimum_height
                BoxLayout:
                    orientation: 'horizontal'
                    size_hint_y: None
                    row_default_height: 200
                    height: self.minimum_height
                    GridLayout:
                        cols:1
                        rows:9
                        size_hint_y: None
                        #size_hint_y: 0.5
                        #row_default_height: 10
                        height: self.minimum_height
                        size_hint_x: 0.5
                        padding: [10, 25] 
                        spacing: [10, 35] 
                        BoxLayout:
                            orientation: 'horizontal'
                            height: self.parent.height * 0.05
                            size_hint_y: None
                            CheckBox:
                                group: 'radio'
                                size_hint_x: 0.3
                                active: root.ids.graph_view.check
                                on_press: root.ids.graph_view.checkbox_check(self, "func1")
                            Label:
                                text: "コメント数"
                                color: [0.23,0.23,0.23,1]
                                size_hint_x: 0.7
                                font_size: 24
                                halign: 'left'
                                valign: 'middle'
                                text_size: self.size
                        BoxLayout:
                            orientation: 'horizontal'
                            height: self.parent.height * 0.05
                            size_hint_y: None
                            CheckBox:
                                group: 'radio'
                                size_hint_x: 0.3
                                active: root.ids.graph_view.check
                                on_press: root.ids.graph_view.checkbox_check(self, "func2")
                            Label:
                                text: "TreeMap"
                                color: [0.23,0.23,0.23,1]
                                size_hint_x: 0.7
                                font_size: 24
                                halign: 'left'
                                valign: 'middle'
                                text_size: self.size
                        BoxLayout:
                            orientation: 'horizontal'
                            height: self.parent.height * 0.05
                            size_hint_y: None
                            CheckBox:
                                group: 'radio'
                                size_hint_x: 0.3
                                active: root.ids.graph_view.check
                                on_press: root.ids.graph_view.checkbox_check(self, "func3")
                            Label:
                                text: "投稿者数"
                                color: [0.23,0.23,0.23,1]
                                size_hint_x: 0.7
                                font_size: 24
                                halign: 'left'
                                valign: 'middle'
                                text_size: self.size
                        BoxLayout:
                            orientation: 'horizontal'
                            height: self.parent.height * 0.05
                            size_hint_y: None
                            CheckBox:
                                group: 'radio'
                                size_hint_x: 0.3
                                active: root.ids.graph_view.check
                                on_press: root.ids.graph_view.checkbox_check(self, "func4")
                            Label:
                                text: "笑い検出"
                                color: [0.23,0.23,0.23,1]
                                size_hint_x: 0.7
                                font_size: 24
                                halign: 'left'
                                valign: 'middle'
                                text_size: self.size
                        BoxLayout:
                            orientation: 'horizontal'
                            height: self.parent.height * 0.05
                            size_hint_y: None
                            CheckBox:
                                group: 'radio'
                                size_hint_x: 0.3
                                active: root.ids.graph_view.check
                                on_press: root.ids.graph_view.checkbox_check(self, "func5")
                            Label:
                                text: "拍手検出"
                                color: [0.23,0.23,0.23,1]
                                size_hint_x: 0.7
                                font_size: 24
                                halign: 'left'
                                valign: 'middle'
                                text_size: self.size
                        # デバッグ用
                        BoxLayout:
                            orientation: 'horizontal'
                            height: self.parent.height * 0.05
                            size_hint_y: None
                            CheckBox:
                                group: 'radio'
                                size_hint_x: 0.3
                                active: root.ids.graph_view.check
                                on_press: root.ids.graph_view.checkbox_check(self, "func6")
                            Label:
                                text: "URL検出"
                                color: [0.23,0.23,0.23,1]
                                size_hint_x: 0.7
                                font_size: 24
                                halign: 'left'
                                valign: 'middle'
                                text_size: self.size
                        BoxLayout:
                            orientation: 'horizontal'
                            height: self.parent.height * 0.05
                            size_hint_y: None
                            CheckBox:
                                group: 'radio'
                                size_hint_x: 0.3
                                active: root.ids.graph_view.check
                                on_press: root.ids.graph_view.checkbox_check(self, "func7")
                            Label:
                                text: "URLランキング"
                                color: [0.23,0.23,0.23,1]
                                size_hint_x: 0.7
                                font_size: 24
                                halign: 'left'
                                valign: 'middle'
                                text_size: self.size
                        BoxLayout:
                            orientation: 'horizontal'
                            height: self.parent.height * 0.05
                            size_hint_y: None
                            CheckBox:
                                group: 'radio'
                                size_hint_x: 0.3
                                active: root.ids.graph_view.check
                                on_press: root.ids.graph_view.checkbox_check(self, "func5")
                            Label:
                                text: "拍手検出"
                                color: [0.23,0.23,0.23,1]
                                size_hint_x: 0.7
                                font_size: 24
                                halign: 'left'
                                valign: 'middle'
                                text_size: self.size

                        BoxLayout:
                            orientation: 'horizontal'
                            height: self.parent.height * 0.05
                            size_hint_y: None
                            CheckBox:
                                group: 'radio'
                                size_hint_x: 0.3
                                active: root.ids.graph_view.check
                                on_press: root.ids.graph_view.checkbox_check(self, "func5")
                            Label:
                                text: "拍手検出"
                                color: [0.23,0.23,0.23,1]
                                size_hint_x: 0.7
                                font_size: 24
                                halign: 'left'
                                valign: 'middle'
                                text_size: self.size
                    Panels:
                        size_hint_x: 0.5
                        size_hint_y: None
                        #pos_hint: {"x":0, "top":1}
                        #size: self.size
                        #height: self.parent.height
                        height: self.minimum_height
                        padding: [10, 30]
                        spacing: [20, 50]
                        id: conpanel

<GraphView>:

<ConfigPanel>:

<SubGrids>:

<Panels>:

<GridLayout>:
    #canvas.before:
    #    BorderImage:
            # BorderImage behaves like the CSS BorderImage
    #        border: 10, 10, 10, 10
    #        source: './Source/image/commentpanel.png'
    #        pos: self.pos
    #        size: self.size